# Generated by Django 4.1.4 on 2023-10-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_picture',
            field=models.FileField(default='avi.jpg', upload_to='static/profile_pic1697281009.6484406'),
        ),
    ]
