# Generated by Django 3.2.25 on 2024-05-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelsapp', '0003_alter_userprofileinfo_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='address',
            field=models.TextField(default='454445', max_length=300),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='city',
            field=models.TextField(default='rtretyuytree', max_length=300),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='contact',
            field=models.BigIntegerField(default=3456676543),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_picture',
            field=models.FileField(default='avi.jpg', upload_to='static/profile_pic1714983297.220271'),
        ),
    ]
