# Generated by Django 3.2.25 on 2024-05-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelsapp', '0004_auto_20240506_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='address',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='city',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='contact',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_picture',
            field=models.FileField(default='20240311_081940.jpg', upload_to='static/profile_pic1714986765.595967'),
        ),
    ]
